FORMAT: 1A
HOST: http:[url]

# QRFoodAPI

Polls is a simple API allowing consumers to view polls and vote in them.

# User Operations [/useroperation/] 
### Register a user [PUT]
Register a new user in the application

+ Request (application/json)

        {
            "firstName": "Test",
            "lastName" : "User",
            "password": "testPass",
            "email": "abc@xyz.com",
            "googleSignIn": <true | false>,
            "fbSignIn": <true | false>,
            "userId": "abcxyz0123"
        }

+ Response 200 (application/json)

    + Body

            {
                "successToken": <1 | 2 | 3>
                "userId": "abcxyz0123",
                "firstName": "Test",
                "lastName" : "User",
                "message" : "<Message>"
            }

### Login a User [POST]
Login a user in the application

+ Request (application/json)

        {
            "email": "abc@xyz.com",
            "password": "testPass",
        }

+ Response 200 (application/json)

    + Body

            {
                "successToken": <1 | 2 | 3>
                "userId": "abcxyz0123",
                "firstName": "Test",
                "lastName" : "User",
                "message": <Message>
            }